name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@latest
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          root_file: algorithm_description.tex
          
